# Generated by Django 4.1 on 2023-09-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date_added',)},
        ),
    ]
